language: node_js

node_js:
  - stable

cache:
  directories:
    - "node_modules"

before_script:
  - npm i

env:
  global:
    - SECRETE_KEY=secrete

script:
  - npm run test

after_success: npm run coverage